language: node_js
node_js:
- stable
cache: 
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_API
  secret_access_key: $AWS_SECRET_KEY
  bucket: "testesi4"
  skip_cleanup: true
  local_dir: build
  acl: public_read
  on:
    branch: main